version: '3.7'

services:
  edit-tracking:
    image: docker.pkg.github.com/williamjacksn/edit-tracking/edit-tracking
    build: .
    ports:
      - 8080:8080

  postgres:
    image: docker.pkg.github.com/williamjacksn/mirror/postgres:11.5-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/11
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
